name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cmake -B build -G Ninja -DBUILD_TESTS=ON -DLLAMA_CCACHE=OFF -DGGML_CCACHE=OFF -DCMAKE_BUILD_TYPE=Release
          else
            cmake -B build -G Ninja -DBUILD_TESTS=ON -DLLAMA_CCACHE=ON -DGGML_CCACHE=ON -DCMAKE_BUILD_TYPE=Release
          fi
        shell: bash
      
      - name: Build
        run: cmake --build build --config Release -j2
      
      - name: Test
        run: ctest --output-on-failure -C Release -j2
        working-directory: build